language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libi2c-dev
      - i2c-tools
      - libffi-dev
install:
  - "pip install -r requirements.txt"
script: nosetests tests
