language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
branches:
  only:
    - master
    - develop
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libi2c-dev i2c-tools python-dev
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script: nosetests tests
